id: A36141737
title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:13:35.081278
  last_modified_at: 2022-03-01 05:13:35.081281
