id: A36141737
title: A Brief Visualization and Recitation of the Great Mother Praj침캐p캐ramit캐
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:13:35.079887
  last_modified_at: 2022-03-01 05:13:35.079894
